{{- range $key, $value := .Values.argocd_projects }}
{{- if include "tpl.isEnabled" $value.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" ($value.syncwave | default "1")
                "extra" ($value.additionalAnnotations | default dict)) | nindent 4 }}
  name: {{ $value.name }}
  namespace: {{ $value.namespace | default "openshift-gitops" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" ($value.additionalLabels | default dict) | indent 4 }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
{{- end }}
{{- end }}
