apiVersion: v2
name: rhacs-backup
description: Chart to create a CronJoc to backup Advanced Cluster Security for Kubernetes to a PerstistentVolume.
version: 1.0.5
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/rhacs-backup
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/backup.png
dependencies:
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - acs
  - security
  - backup
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
