{{- if include "tpl.isEnabled" .Values.quay.enabled }}
{{- with .Values.quay }}
{{- if include "tpl.isEnabled" .job_inject_route_cert.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .job_inject_route_cert.serviceAccount | default "quay-ca-injector" }}
  namespace: {{ $.Values.quay.namespace.name | quote }}
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
  annotations:
    {{- include "quay.hookAnnotations"
          (dict "syncWave" (.job_inject_route_cert.syncwave | default "5")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
