{{- if include "tpl.isEnabled" .Values.quay.enabled }}
{{- with .Values.quay }}
{{- if include "tpl.isEnabled" .job_inject_route_cert.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
  annotations:
    {{- include "quay.hookAnnotations"
          (dict "syncWave" (.job_inject_route_cert.syncwave | default "5")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  name: {{ .job_inject_route_cert.serviceAccount | default "quay-ca-injector" }}-role
  namespace: {{ $.Values.quay.namespace.name | quote }}
rules:
- verbs:
  - get
  - list
  - patch
  apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
{{- end }}
{{- end }}
{{- end }}
