{{- range $key,$val := .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $key }}
{{- if $.Values.default.app.namespace }}
  namespace: {{ $.Values.default.app.namespace }}
{{- end }}
{{- if $val.labels  }}
  labels:
{{- with $val.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

{{- if or $val.annotations }}
  annotations:
{{- with $val.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
{{- if $val.extraFields }}
{{ tpl $val.extraFields $ | trim | indent 2 }}
{{- end }}
  description: {{ tpl $val.description $ }}
  sourceRepos:
{{ toYaml $val.sourceRepos | indent 4 }}
{{- if $val.roles }}
  roles:
{{- tpl $val.roles $ | indent 4 }}
{{- else if (($.Values.default.project).roles) }}
  roles:
{{ tpl $.Values.default.project.roles $ | indent 4 }}
{{- end }}
{{- if $val.destinations }}
  destinations:
{{ tpl $val.destinations $ | indent 4 }}
{{- else if $.Values.default.project.destinations }}
  destinations:
{{ tpl $.Values.default.project.destinations $ | indent 4 }}
{{- end }}
{{- end }}