{{- with .Values }}
{{ if include "tpl.isEnabled" .enabled }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .storageclass_name }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.additionalLabels | default dict) | indent 4 }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.syncwave | default 1)
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
provisioner: openshift-storage.noobaa.io/obc
parameters:
  bucketclass: {{ .backingstore_name }}-class
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}
{{- end }}
