{{ if eq (.Values.compliance.scansettingbinding.tailored.enabled | toString) "true" }}
{{- range $key, $value := .Values.compliance.scansettingbinding.tailored.modified_profiles }}
---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Values.compliance.namespace.name | default "openshift-compliance" | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.compliance.scansettingbinding.syncwave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
spec:
  description: {{ $value.description }}
  {{ if $value.disableRules }}
  disableRules:
  {{- range $rule := $value.disableRules }}
    - name: {{ $rule.name }}
      rationale: {{ $rule.rationale | quote }}
  {{- end }}
  {{- end }}
  {{ if $value.setValues }}
  setValues:
  {{- range $val := $value.setValues }}
    - name: {{ $val.name }}
      rationale: {{ $val.rationale | quote }}
      value: {{ $val.value | quote }}
  {{- end }}
  {{- end }}
  extends: {{ $value.extends }}
  title: {{ $value.title }}
{{- end }}
{{- end }}