{{- if include "tpl.isEnabled" .Values.compliance.scansettingbinding.tailored.enabled }}
{{- range $key, $value := .Values.compliance.scansettingbinding.tailored.modified_profiles }}
---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Values.compliance.namespace.name | default "openshift-compliance" | quote }}
  annotations:
    {{- include "tpl.argocdMetadata"
           (dict "syncWave" $.Values.compliance.scansettingbinding.syncwave
                 "syncOptions" ($.Values.compliance.scansettingbinding.syncOptions | default "SkipDryRunOnMissingResource=true")
                 "extra" ($.Values.compliance.scansettingbinding.tailored.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" $.Values.compliance.scansettingbinding.tailored.additionalLabels | indent 4 }}
spec:
  description: {{ $value.description }}
  {{ if $value.disableRules }}
  disableRules:
  {{- range $rule := $value.disableRules }}
    - name: {{ $rule.name }}
      rationale: {{ $rule.rationale | quote }}
  {{- end }}
  {{- end }}
  {{ if $value.setValues }}
  setValues:
  {{- range $val := $value.setValues }}
    - name: {{ $val.name }}
      rationale: {{ $val.rationale | quote }}
      value: {{ $val.value | quote }}
  {{- end }}
  {{- end }}
  extends: {{ $value.extends }}
  title: {{ $value.title }}
{{- end }}
{{- end }}
