kind: Service
apiVersion: v1
metadata:
  name: cyclonedx-bom-repo-server
  namespace: {{ .Values.namespace.name | quote }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.Values.syncwave | default "0")
                "extra" (.Values.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.Values.additionalLabels | default dict) | indent 4 }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: cyclonedx-bom-repo-server
