{{ if include "tpl.isEnabled" .Values.rhacm.multiclusterhub.enabled }}
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: {{ .Values.rhacm.namespace.name | quote | default ("open-cluster-management") }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.Values.rhacm.multiclusterhub.additionalLabels | default dict) | nindent 4 }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.Values.rhacm.multiclusterhub.syncwave | default "3")
                "extra" (.Values.rhacm.multiclusterhub.additionalAnnotations | default dict)) | nindent 4 }}
spec:
  availabilityConfig: {{ .Values.rhacm.multiclusterhub.availabilityConfig | default ("Basic") }}

{{- if .Values.rhacm.multiclusterhub.nodeSelector }}
{{- include "tpl.nodeSelector" .Values.rhacm.multiclusterhub | indent 2 }}
{{- end }}

  {{- if .Values.rhacm.multiclusterhub.tolerations }}
{{ include "tpl.tolerations" .Values.rhacm.multiclusterhub.tolerations | indent 2 }}
  {{- end }}

{{- end }}
