{{- if .Values.rhacm.search }}
{{- if include "tpl.isEnabled" .Values.rhacm.search.enabled }}
---
apiVersion: search.open-cluster-management.io/v1alpha1
kind: Search
metadata:
  name: search-v2-operator
  namespace: {{ .Values.rhacm.namespace.name | default "open-cluster-management" | quote }}
  labels:
    cluster.open-cluster-management.io/backup: ""
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.Values.rhacm.search.additionalLabels | default dict) | nindent 4 }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.Values.rhacm.search.syncwave | default "15")
                "extra" (.Values.rhacm.search.additionalAnnotations | default dict)) | nindent 4 }}
spec:
{{- with .Values.rhacm.search.dbStorage }}
  dbStorage:
    size: {{ .size | default "10Gi" | quote }}
{{- if .storageClassName }}
    storageClassName: {{ .storageClassName | quote }}
{{- end }}
{{- end }}
{{- $dep := .Values.rhacm.search.deployments }}
{{- if and $dep (not (empty $dep)) }}
  deployments:
{{- toYaml $dep | nindent 4 }}
{{- end }}
{{- if .Values.rhacm.search.nodeSelector }}
{{- include "tpl.nodeSelector" .Values.rhacm.search | indent 2 }}
{{- end }}
{{- if .Values.rhacm.search.tolerations }}
{{ include "tpl.tolerations" .Values.rhacm.search.tolerations | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
