{{- if include "tpl.isEnabled" .Values.collector.enabled }}
{{- if .Values.collector.serviceAccount }}
{{- if include "tpl.isEnabled" .Values.collector.serviceAccount.create }}
{{- with .Values.collector }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name }}
  namespace: {{ $.Values.namespace.name }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.syncwave | default "10")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/instance: {{ .name }}
    {{- include "tpl.additionalLabels" (.additionalLabels | default dict) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
