{{- range .Values.ingresscontrollers }}
{{ if include "tpl.isEnabled" .enabled }}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: {{ .name }}
  namespace: openshift-ingress-operator
  annotations:
    {{- $extra := .additionalAnnotations | default dict }}
    {{- if kindIs "map" .annotations }}
    {{- $extra = merge $extra .annotations }}
    {{- end }}
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.syncwave | default "10")
                "extra" $extra) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" .additionalLabels | indent 4 }}
spec:
  replicas: {{ .replicas | default "2" }}
  {{- if .defaultCertificate }}
  defaultCertificate:
    name: {{ .defaultCertificate }}
  {{- end }}
  {{- if .domain }}
  domain: {{ .domain }}
  {{- end }}
  {{- if .routeAdmission }}
  routeAdmission:
    {{- if .routeAdmission.namespaceOwnership }}
    namespaceOwnership: {{ .routeAdmission.namespaceOwnership }}
    {{- end }}
    {{- if .routeAdmission.namespaceSelector }}
    {{- end }}
    {{- if .routeAdmission.wildcardPolicy }}
    wildcardPolicy: {{ .routeAdmission.wildcardPolicy }}
    {{- end }}
  {{- end }}

  {{- if .endpointPublishingStrategy }}
  endpointPublishingStrategy:
    type: {{ .endpointPublishingStrategy.type | default "HostNetwork" }}
    {{- if .endpointPublishingStrategy.hostNetwork }}
    hostNetwork:
      httpPort: {{ .endpointPublishingStrategy.hostNetwork.httpPort }}
      httpsPort: {{ .endpointPublishingStrategy.hostNetwork.httpsPort }}
      statsPort: {{ .endpointPublishingStrategy.hostNetwork.statsPort }}
    {{- end }}
  {{- end }}
  {{- if .tlsSecurityProfile }}
  tlsSecurityProfile:
    {{- toYaml .tlsSecurityProfile | nindent 4 }}
  {{- end }}
  {{- if .namespaceSelector }}
  namespaceSelector:
    matchExpressions:
      {{- range .namespaceSelector.matchExpressions }}
      {{- include "tpl.matchExpressions" . }}
      {{- end }}
  {{- end }}

  {{- if .nodePlacement }}
  {{- with .nodePlacement }}
  nodePlacement:
    {{- if .nodeSelector }}
    nodeSelector:
      matchLabels:
        {{ .nodeSelector.key }}: {{ .nodeSelector.value | quote }}
    {{- end }}

  {{- if .tolerations }}
{{ include "tpl.tolerations" .tolerations | indent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
