{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
{{- if $value.operatorgroup.create }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $key | default "demo-operator-group" | quote }}
  namespace: {{ $value.namespace.name | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-operator.labels" $value | nindent 4 }}
  annotations:
    {{- include "helper-operator.annotations" $value | nindent 4 }}
{{- /* Configure the operatorgroup for all Namespaces or for the "Home" namespace */ -}}
{{- if $value.operatorgroup.notownnamespace }}
spec: {}
{{- else }}
spec:
  targetNamespaces:
  - {{ $value.namespace.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}