{{- range $key, $value := .Values.operators }}
{{- if eq ($value.enabled | toString) "true" }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $key | quote }}
  namespace: {{ $value.namespace.name | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-operator.labels" $value | nindent 4 }}
  annotations:
    {{- include "helper-operator.annotations" $value | nindent 4 }}
spec:
  {{- /* Main settings for the Operator */}}
  channel: {{ $value.subscription.channel | default "stable" | quote }}
  installPlanApproval: {{ $value.subscription.approval | default "Automatic" | quote }}
  name: {{ $value.subscription.operatorName | quote }}
  source: {{ $value.subscription.source | default "redhat-operators" | quote }}
  sourceNamespace: {{ $value.subscription.sourceNamespace | default "openshift-marketplace" | quote }}

  {{- /* additional and optional settings for the Operator */}}
  {{- include "helper-operator.subscription.config" $value.subscription | nindent 2 }}

{{- if $value.subscription.csv }}
  startingCSV: {{ $value.subscription.csv }}
{{- end }}
{{- end }}
{{- end }}
