{{- range $key, $value := .Values.operators }}
{{- if eq ($value.enabled | toString) "true" }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $key | quote }}
  namespace: {{ $value.namespace.name | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "0" | quote }}
spec:
  {{- /* Main settings for the Operator */}}
  channel: {{ $value.subscription.channel | default "stable" | quote }}
  installPlanApproval: {{ $value.subscription.approval | default "Automatic" | quote }}
  name: {{ $value.subscription.operatorName | quote }}
  source: {{ $value.subscription.source | default "redhat-operators" | quote }}
  sourceNamespace: {{ $value.subscription.sourceNamespace | default "openshift-marketplace" | quote }}

  {{- /* additional and optional settings for the Operator */}}
  {{- if $value.subscription.config }}
  config:
    {{- /* Define a nodeSelector if required */}}
    {{- if $value.subscription.config.nodeSelector }}
    nodeSelector:
      {{ $value.subscription.config.nodeSelector.key }}: {{ $value.subscription.config.nodeSelector.value | quote }}
    {{- end }}

    {{- /* Define required tolerations */}}
    {{- if $value.subscription.config.tolerations }}
{{ include "tpl.tolerations" $value.subscription.config.tolerations | indent 4 }}
    {{- end }}
    {{- if $value.subscription.config.env }}

    {{- /* Define additional environment variables, that might configure the Operator */}}
    env:
      {{- toYaml $value.subscription.config.env | nindent 6 }}
    {{- end }}

    {{- /* mount additional volumes for certificates for the Operator */}}
    {{- if $value.subscription.config.trustedCA }}
    {{- if eq ( $value.subscription.config.trustedCA.enabled | toString) "true" }}
    volumeMounts:
      - name: {{ $value.subscription.config.trustedCA.configMap | default "trusted-ca-bundle" }}
        mountPath: /etc/pki/ca-trust/extracted/pem
        readOnly: true
    volumes:
      - name: {{ $value.subscription.config.trustedCA.configMap | default "trusted-ca-bundle" }}
        configMap:
          name: {{ $value.subscription.config.trustedCA.configMap | default "trusted-ca-bundle" }}
          items:
            - key: {{ $value.subscription.config.trustedCA.configMapKey | default "ca-bundle.crt" }}
              path: {{ $value.subscription.config.trustedCA.configMapPath | default "ca-bundle.crt" }}
    {{- end }}
    {{- end }}

    {{- /* Define resource limits and requests for the Operator */}}
    {{- if $value.subscription.config.resources }}
{{ include "tpl.resources" $value.subscription.config.resources | indent 4 }}
    {{- end }}

  {{- end }}
{{- if $value.subscription.csv }}
  startingCSV: {{ $value.subscription.csv }}
{{- end }}
{{- end }}
{{- end }}
