{{- with .Values.quay }}
{{- if include "tpl.isEnabled" .job_init_quay.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .job_init_quay.serviceAccount }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
  annotations:
    {{- include "quay.hookAnnotations"
          (dict "syncWave" (.job_init_quay.syncwave | default "200")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
{{- end }}
{{- end }}