{{- with .Values.quay }}
{{- if include "tpl.isEnabled" .job_init_quay.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .job_init_quay.serviceAccount }}-rb
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
  annotations:
    {{- include "quay.hookAnnotations"
          (dict "syncWave" (.job_init_quay.syncwave | default "200")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .job_init_quay.serviceAccount }}-role
subjects:
- kind: ServiceAccount
  name: {{ .job_init_quay.serviceAccount }}
  namespace: {{ .namespace.name | quote }}
{{- end }}
{{- end }}
