{{- with .Values.quay }}
{{- if include "tpl.isEnabled" .job_init_quay.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
  annotations:
    {{- include "quay.hookAnnotations"
          (dict "syncWave" (.job_init_quay.syncwave | default "200")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  name: {{ .job_init_quay.serviceAccount }}-role
  namespace: {{ .namespace.name | quote }}
rules:
- verbs:
  - get
  - list
  apiGroups:
  - apps
  resources:
  - deployments
- verbs:
  - get
  - list
  apiGroups:
  - ''
  resources:
  - secrets
- verbs:
  - get
  - list
  apiGroups:
  - route.openshift.io
  resources:
  - routes
{{- end }}
{{- end }}
