{{- if include "tpl.isEnabled" .Values.quay.enabled }}
{{- if include "tpl.isEnabled" .Values.quay.init_user.enabled }}
{{- with .Values.quay }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .init_user.secretName | default "init-user" }}
  namespace: {{ .namespace.name }}
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
  annotations:
    {{- include "quay.syncAnnotations"
          (dict "syncWave" (.job_init_quay.syncwave | default "200")
                "compareOptions" "IgnoreExtraneous"
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
data:
  mail: {{ .init_user.mail | default "admin@company.com" | b64enc }}
  username: {{ .init_user.username | default "admin" | b64enc }}
  {{- if .init_user.password }}
  password: {{ .init_user.password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
{{- end }}
{{- end }}
