{{- with .Values.apiserver  }}
{{ if include "tpl.isEnabled" .enabled }}
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  name: cluster
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
spec:
  {{- if .audit }}
  audit:
    profile: {{ .audit.profile | default "Default" }}
  {{- end }}
  {{- if include "tpl.isEnabled" .etcd_encryption.enabled }}
  encryption:
    type: {{ .etcd_encryption.encryption_type | default "aesgcm" }}
  {{- end }}
  {{- if include "tpl.isEnabled" .custom_cert.enabled }}
  servingCerts:
    namedCertificates:
      - names:
          {{- range .custom_cert.cert_names }}
          - {{ . }}
          {{- end }}
        servingCertificate:
          name: {{ .custom_cert.secretname | default "api-certificate" }}
  {{- end }}
{{- end }}
{{- end }}
