{{- with .Values.idp }}
{{ if include "tpl.isEnabled" .enabled }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
spec:
{{- if include "tpl.isEnabled" .customloginpage.enabled }}
  templates:
    login:
      name: {{ .customloginpage.secretname }}
    {{- if .customloginpage.secretname_providerpage }}
    providerSelection:
      name: {{ .customloginpage.secretname_providerpage }}
    {{- end }}
{{- end }}
{{- if .providers }}
{{- if include "tpl.isEnabled" .providers.enabled }}
  identityProviders:
{{- with .providers }}
{{- range $key, $value := .ldap -}}
{{ if include "tpl.isEnabled" $value.enabled }}
  - ldap:
      attributes:
      {{- if .attributes }}
        {{- toYaml .attributes | nindent 8 }}
      {{- else }}
        email:
        - mail
        id:
        - dn
        name:
        - cn
      {{- end }}
        preferredUsername:
        {{- range .preferredusername }}
        - {{ . | quote }}
        {{- end }}
      bindDN: {{ .binddn | quote }}
      bindPassword:
        name: {{ .secretname | default "ldap-secret" }}
      ca:
        name: {{ .cmname | default "ca-config-map" }}
      insecure: {{ .insecure | default true }}
      url: {{ .url | quote }}
    mappingMethod: claim
    name: {{ .name | default "ldap" | quote }}
    type: LDAP
{{- end }}
{{- end }}
{{- end }}
{{- with .providers }}
{{- range $key, $value := .htpasswd -}}
{{ if include "tpl.isEnabled" $value.enabled }}
  - htpasswd:
      fileData:
        name: {{ .secretname | default "htpasswd-secret" }}
    mappingMethod: claim
    name: {{ .name | default "htpasswd" | quote }}
    type: HTPasswd
{{- end }}
{{- end }}
{{- end }}

{{- with .providers }}
{{- range $key, $value := .google -}}
{{ if include "tpl.isEnabled" $value.enabled }}
  - google:
      clientID: {{ .clientID | quote }}
      clientSecret:
        name: {{ .secretname | default "google-secret" }}
      hostedDomain: {{ .hostedDomain | default "my.com" | quote }}
    mappingMethod: {{ .mappingMethod | default "claim" | quote }}
    name: {{ .name | default "sso" | quote }}
    type: Google
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
