{{/*
Trusted CA Certificates ConfigMap
This template creates a ConfigMap containing trusted CA certificates for the cluster proxy.
The ConfigMap is referenced by the Proxy resource's trustedCA field.

Only PEM formatted certificates are supported in the ca-bundle.crt key.
*/}}
{{- with .Values.clusterproxy }}
{{- if and .enabled .trustedCA .trustedCACerts }}
{{- /* Validate trustedCA is a valid Kubernetes name */ -}}
{{- if not (regexMatch "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" .trustedCA) }}
{{- fail "clusterproxy.trustedCA must be a valid Kubernetes resource name" }}
{{- end }}
{{- /* Validate that trustedCACerts contains valid PEM content */ -}}
{{- if not .trustedCACerts.content }}
{{- fail "clusterproxy.trustedCACerts.content is required and must contain PEM formatted certificates" }}
{{- end }}
{{- if not (contains "-----BEGIN CERTIFICATE-----" .trustedCACerts.content) }}
{{- fail "clusterproxy.trustedCACerts.content must contain valid PEM formatted certificates" }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .trustedCA | quote }}
  namespace: openshift-config
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    config.openshift.io/inject-trusted-cabundle: "true"
    {{- include "tpl.additionalLabels" .additionalLabels | indent 4 }}
  annotations:
    {{- include "tpl.additionalAnnotations" .additionalAnnotations | indent 4 }}
data:
  {{- if .trustedCACerts }}
  ca-bundle.crt: |
{{ .trustedCACerts.content | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
