{{- range $key, $value := .Values.namespaces }}
{{- if include "tpl.isEnabled" .enabled }}
{{- if .local_admin_group }}
{{- if include "tpl.isEnabled" .local_admin_group.enabled }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ if .local_admin_group.group_name }}{{ .local_admin_group.group_name | replace "_" "-" }}{{- else }}{{ .name | replace "_" "-" }}-rb{{- end }}
  namespace: {{ .name | replace "_" "-" }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ if .local_admin_group.group_name }}{{ .local_admin_group.group_name | replace "_" "-" }}{{- else }}{{ .name | replace "_" "-" }}-admins{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .local_admin_group.clusterrole | default "admin" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}