{{- range $key, $value := .Values.namespaces }}
{{- if include "tpl.isEnabled" .enabled }}
{{- if .local_admin_group }}
{{- if include "tpl.isEnabled" .local_admin_group.enabled }}
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: {{ if .local_admin_group.group_name }}{{ .local_admin_group.group_name | replace "_" "-" }}{{- else }}{{ .name | replace "_" "-" }}-admins{{- end }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
users:
  {{- range .local_admin_group.users }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}