{{- if eq (.Values.enabled | toString) "true" }}
{{- if eq (.Values.cronjobKeyPruner.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rolename | default "key-pruner" }}
  namespace: openshift-kube-apiserver
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - "secrets"
  verbs: ["get", "list", "create", "delete", "watch", "patch", "update"]
{{- end }}
{{- end }}