apiVersion: v2
name: rhacm-setup
description: Setup and configure Advanced Cluster Managerment. Replaces the Chart rhacm-full-stack.
version: 1.0.18
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/rhacm-setup
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/acm.png
dependencies:
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - clustermanagement
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
    - kind: added
      description: support for tolerations in MultiClusterHub CRD
    - kind: added
      description: updated to helper-status-chcker v4
    - kind: added
      description: README
    - kind: added
      description: added tpl chart
    - kind: added
      description: switching some snippets to use global tpl
    - kind: added
      description: added support for nodeSelector of the Main instance
