---
override-rhacm-operator-version: &rhacmversion release-2.8

# Install Operator RHACM
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    advanced-cluster-management:
      enabled: false
      syncwave: '0'
      namespace:
        name: open-cluster-management
        create: true
      subscription:
        channel: *rhacmversion
        approval: Automatic
        operatorName: advanced-cluster-management
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false
        notownnamespace: false

helper-status-checker:
  enabled: false

  operatorName: advanced-cluster-management

  # space separate list of deployments which shall be checked for status
  deployments: "multicluster-operators-application multicluster-observability-operator multicluster-operators-channel multicluster-operators-hub-subscription multicluster-operators-standalone-subscription multicluster-operators-subscription-report multiclusterhub-operator submariner-addon"

  wait_time: 60  # wait time in seconds for the check-job to verify when the deployments should be ready

  namespace:
    name: open-cluster-management

  serviceAccount:
    create: false
    name: "status-checker"

rhacm:
  # Namespace
  # Should be installed in open-cluster-management (default)
  namespace:
    name: open-cluster-management
  multiclusterhub:
    enabled: false
    syncwave: '3'

    # Specifies deployment replication for improved availability. Options are: Basic and High
    # Default: Basic
    # availabilityConfig: High

    # If you want this component to only run on specific nodes, you can
    # configure tolerations of tainted nodes.
    # tolerations:
    #  - effect: NoSchedule
    #    key: infra
    #    operator: Equal
    #    value: reserved
