{{- if include "tpl.isEnabled" .Values.netobserv.enabled }}
{{- with .Values.netobserv }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netobserv-reader
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.rbacSyncwave | default "3")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.additionalLabels | default dict) | nindent 4 }}
rules:
- apiGroups:
  - 'loki.grafana.com'
  resources:
  - network
  resourceNames:
  - logs
  verbs:
  - 'get'
{{- end }}
{{- end }}
