apiVersion: v2
name: ingresscontroller
description: Configures the IngressController object.
version: 1.0.17
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/ingresscontroller
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/settings-icon.png
dependencies:
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - generic
  - clusterconfig
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Possibility to configure allowed registries
    - kind: added
      description: added new type of etcd encryption, monitoring stack configuration etc.
    - kind: added
      description: added README
    - kind: added
      description: added tpl chart
    - kind: added
      description: added defaultCertificate option to use a valid certificate for the ingresscontroller
    - kind: added
      description: added possibility to define annotations for the IngressController. For example to enable HTTP/2
    - kind: added
      description: added option to configure namespaceSelector, endpointPublishingStrategy, tlsSecurityProfile and domain
    - kind: added
      description: added option to configure routeAdmission
