{{- if include "tpl.isEnabled" .Values.enabled }}
{{- if .Values.serviceAccount }}
{{- if include "tpl.isEnabled" .Values.serviceAccount.create }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name | default "acs-backup" }}
  namespace: stackrox
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
