apiVersion: v2
name: cost-management
description: Setup and configure cost-management Operator
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/network-observability
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/cost-mgmt-icon.png
version: 1.0.12
dependencies:
  - name: helper-operator
    version: ~1.0.21
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - configuration
  - cost-management
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial Release
    - kind: added
      description: Added README and additional possible parameters
    - kind: added
      description: updated to helper-status-checker v4
    - kind: added
      description: added dependency tp tpl library
    - kind: added
      description: added source configuration parameter
    - kind: fixed
      description: fixed auth_secret parameter
