{{- with .Values.quay_configuration }}
{{- if include "tpl.isEnabled" .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-config-secret-sa
  namespace: quay-enterprise
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "type" "hook"
                "syncWave" (.syncwave | default 3)
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
{{- end }}
{{- end }}
