{{- with .Values.quay_configuration }}
{{- if include "tpl.isEnabled" .enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-config-secret-crb
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "type" "hook"
                "syncWave" (.syncwave | default 3)
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .additionalLabels) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: create-config-secret-sa
    namespace: {{ $.Values.quay.namespace.name }}
{{- end }}
{{- end }}
