{{ if include "tpl.isEnabled" .Values.enabled }}
{{- with .Values }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-odf-secret-sa
  namespace: {{ .namespace }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "type" "hook"
                "syncWave" (.syncwave | default 3)
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.additionalLabels | default dict) | indent 4 }}
{{- end }}
{{- end }}
