{{- with .Values.certManager }}
{{- if include "tpl.isEnabled" .enable_patch }}
---
apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.additionalLabels | default dict) | indent 4 }}
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.syncwave | default "10")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
spec:
  logLevel: {{ .logLevel | default "Normal" }}
  operatorLogLevel: {{ .operatorLogLevel | default "Normal" }}
  managementState: Managed
  observedConfig: null
  controllerConfig:
    {{- if include "tpl.isEnabled" .overrideArgs.enabled }}
    overrideArgs:
      {{- range .overrideArgs.args }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- if .unsupportedConfigOverrides }}
  unsupportedConfigOverrides:
{{- toYaml .unsupportedConfigOverrides | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
