apiVersion: v2
name: openshift-data-foundation
description: Deploys and configures the OpenShift Data Foundation Operator.
version: 1.0.34
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/openshift-data-foundation
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/redhat-icon.png
dependencies:
  - name: helper-operator
    version: ~1.0.14
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - storage
  - odf
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
    - kind: added
      description: Updated to Open Data Foundation v4.13
    - kind: added
      description: Added StorageCluster object which automatically spins up the storage.
    - kind: added
      description: Spliting storagecluster to full-fletched and standalone for better reasability.
    - kind: fixed
      description: wrong IFs
    - kind: added
      description: updated to helper-status-check v4 and added readme
    - kind: added
      description: added tpl chart
    - kind: added
      description: added resourceProfile setting that can be set to lean or balanced or performance
