apiVersion: v2
name: sealed-secrets
description: A Helm chart to deploy sealed-secrets - depends on Bitnami's helm chart
type: application
version: 1.0.24
appVersion: 1.0.0
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/sealed-secrets
icon: https://avatars.githubusercontent.com/u/34656521?s=200&v=4
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
dependencies:
  - name: sealed-secrets
    version: "2.17.7"
    repository: https://bitnami-labs.github.io/sealed-secrets
    condition: sealed-secrets.enabled
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
keywords:
  - secretmanagement
  - security
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
    - kind: added
      description: updated sealed secrets helm chart version
    - kind: added
      description: new README
    - kind: added
      description: new version of sealed secrets chart 2.16
    - kind: added
      description: added tpl chart
