{{- with .Values.storagecluster }}
{{- if include "tpl.isEnabled" .enabled }}
{{- if include "tpl.isEnabled" .multigateway_only.enabled }}
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    {{- include "tpl.argocdMetadata"
          (dict "syncWave" (.syncwave | default "3")
                "extra" (.additionalAnnotations | default dict)) | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" (.additionalLabels | default dict) | nindent 4 }}
spec:
  multiCloudGateway:
    dbStorageClassName: {{ .multigateway_only.storageclass }}
    reconcileStrategy: standalone

{{- end }}
{{- end }}
{{- end }}
