apiVersion: v2
name: openshift-virtualization
description: Configure the operator Openshift Virtualization (HyperConverged and HostPath Provisioner)
version: 1.0.0
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/openshift-virtualization
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/ocp-virt-icon.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
dependencies:
  - name: tpl
    version: ~1.0.23
    repository: https://charts.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - openshift
  - virtualization
  - hyperconverged
  - kubevirt
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: initial release
