{{- with .Values }}
{{ if include "tpl.isEnabled" .enabled }}
{{- range .checks }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{- include "helper-status-checker.hookAnnotations" (dict "values" $.Values "check" .) | nindent 4 }}
  name: {{ .serviceAccount.name }}-{{ .namespace.name }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-status-checker.labels" $.Values | indent 4 }}
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - installplans
      - subscription
      - subscriptions
    verbs:
      - get
      - list
      - patch
{{- end }}
{{- end }}
{{- end }}
