{{- if include "tpl.isEnabled" .Values.quay.enabled }}
{{- if include "tpl.isEnabled" .Values.quay.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.quay.namespace.syncwave | default "0" | quote }}
    openshift.io/display-name: {{ .Values.quay.namespace.descr | default "" | quote }}
    {{- if .Values.quay.namespace.bindtoNode }}
    {{- if .Values.quay.namespace.bindtoNode.role }}
    {{- include "tpl.bindtoNode" .Values.quay.namespace.bindtoNode | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- include "tpl.additionalAnnotations" (.Values.quay.additionalAnnotations | default dict) | nindent 4 }}
  name: {{ .Values.quay.namespace.name }}
  labels:
    openshift.io/cluster-monitoring: "true"
    {{- include "quay.labels" (dict "root" $ "additionalLabels" .Values.quay.additionalLabels) | nindent 4 }}
{{- end }}
{{- end }}
