{{- if eq (.Values.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterrolename | default "cluster-etcd-backup" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
     - "nodes"
     - namespaces
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
     - "pods"
     - "pods/log"
     - pods/attach
  verbs: ["get", "list", "create", "delete", "watch"]
{{- end }}
