
{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
{{ if eq ($value.namespace.create | toString) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $value.namespace.name | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-operator.namespace.labels" $value | nindent 4 }}
  annotations:
  {{- if or ($value.namespace.descr) ($value.namespace.displayname) }}
    {{- if $value.namespace.descr }}
    openshift.io/description: {{ $value.namespace.descr }}
    {{- end }}
    {{- if $value.namespace.displayname }}
    openshift.io/display-name: {{ $value.namespace.displayname }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}