{{- if .Values.console_plugins }}
{{- if eq (.Values.console_plugins.enabled | toString) "true" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: enable-console-plugin-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Values.console_plugins.job_namespace | default "kube-system" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-operator.labels" .Values.console_plugins | nindent 4 }}
  annotations:
    {{- include "helper-operator.job.annotations" .Values.console_plugins | nindent 4 }}
spec:
  selector: {}
  template:
    metadata:
      name: enable-console-plugin
    spec:
      containers:
        - name: enable-console-plugin
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
          
              set -euo pipefail  # Add error handling
              
              # More efficient plugin check and update
              
              new_values=({{ join " " .Values.console_plugins.plugins }})
              
              current_plugins=$(oc get console.operator cluster -o jsonpath='{.spec.plugins}' 2>/dev/null || echo "[]")
              
              for value in "${new_values[@]}"; do
              
                if echo "$current_plugins" | grep -q "\"$value\""; then
              
                  echo "Plugin $value is already configured."
              
                else
              
                  echo "Adding plugin $value..."
              
                  oc patch console.operator cluster --type json -p "[{\"op\": \"add\", \"path\": \"/spec/plugins/-\", \"value\": \"$value\"}]"
              
                  echo "Plugin $value has been added"

                fi

              done
      restartPolicy: Never
      serviceAccountName: enable-console-plugin-sa
{{- end }}
{{- end }}
