{{- if .Values.console_plugins }}
{{- if eq (.Values.console_plugins.enabled | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.console_plugins.job_service_account | default "enable-console-plugin-sa" }}
  namespace: {{ .Values.console_plugins.job_namespace | default "kube-system" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-operator.labels" .Values.console_plugins | nindent 4 }}
  annotations:
    {{- include "helper-operator.job.annotations" .Values.console_plugins | nindent 4 }}
{{- end }}
{{- end }}
