{{- if .Values.console_plugins }}
{{- if eq (.Values.console_plugins.enabled | toString) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.console_plugins.job_service_account_crb | default "enable-console-plugin-crb" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "helper-operator.labels" .Values.console_plugins | nindent 4 }}
  annotations:
    {{- include "helper-operator.job.annotations" .Values.console_plugins | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.console_plugins.job_service_account_role | default "enable-console-plugin-role" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.console_plugins.job_service_account | default "enable-console-plugin-sa" }}
    namespace: {{ .Values.console_plugins.job_namespace | default "kube-system" }}
{{- end }}
{{- end }}
