---
# Examples values file

# -- If you want this component to only run on specific nodes, you can
# configure tolerations of tainted nodes.
# <br />
# Example include:
# {{- if .Values.tolerations }}
# {{ include "tpl.tolerations" .Values.tolerations  | indent 0 }}
# {{- end }}
tolerations:
  - effect: NoSchedule
    key: infra
    operator: Equal
    value: reserved
    tolerationSeconds: 600
  - effect: NoSchedule
    key: infra
    operator: Equal
    value: reserved
    tolerationSeconds: 600

# -- If you want to define resources
# <br />
# Example include:
# {{- if .Values.resources }}
# {{ include "tpl.resources" .Values.resources  | indent 0 }}
# {{- end }}
resources:
  requests:
    cpu: 4
    memory: 8
    ephemeral-storage: 50
  limits:
    cpu: 8
    memory: 16
    ephemeral-storage: 500
    nvidia: 1

nodeSelector:
  key: node-role.kubernetes.io/infra
  value: ''

# -- If you want to annotate a namespace to run on a specific node configure the following annotations
# <br />
# Example include:
#    {{- if .Values.namespace.bindtoNode }}
#    {{- if .Values.namespace.bindtoNode.role }}
#    {{- include "tpl.bindtoNode" .Values.namespace.bindtoNode | nindent 4 }}
#    {{- end }}
#    {{- end }}
#    {{- include "tpl.additionalAnnotations" .Values.namespace.additionalAnnotations | indent 4 }}
#    {{- include "tpl.additionalLabels" .Values.namespace.additionalLabels | indent 4 }}

namespace:
  bindtoNode:
    role: infra
  additionalAnnotations:
    additionalAnnotation1: "My Annotation"
    additionalAnnotation2: "My Annotation 2"
  additionalLabels:
    myLabel1: "My Label"
    myLabel2: "My Labe 2"

# -- Define a NamespaceSelector and the required labels
# <br />
# Example include (used in chart admin-networkpolicies)
#
#spec:
#  subject:
#    {{- if .subject.namespaces }}
#    namespaces:
#      {{- if .subject.namespaces.matchExpressions }}
#      matchExpressions:
#        {{- range .subject.namespaces.matchExpressions }}
#        {{- include "tpl.matchExpressions" . | indent 4 }}
#        {{- end }}
#      {{- end }}
#      {{- if .subject.namespaces.matchLabels }}
#      {{- include "tpl.matchLabels" .subject.namespaces.matchLabels | indent 4 }}
#      {{- end }}
#    {{- end }}
namespaceSelector:          
  matchLabels:
    kubernetes.io/metadata.name: "openshift-dns"

# -- Deine a metchExpression to use key, oeprator, value pairs.
# <br />
# Example include (used in chart admin-networkpolicies)
#
#spec:
#  subject:
#    {{- if .subject.namespaces }}
#    namespaces:
#      {{- if .subject.namespaces.matchExpressions }}
#      matchExpressions:
#        {{- range .subject.namespaces.matchExpressions }}
#        {{- include "tpl.matchExpressions" . | indent 4 }}
#        {{- end }}
#      {{- end }}
#      {{- if .subject.namespaces.matchLabels }}
#      {{- include "tpl.matchLabels" .subject.namespaces.matchLabels | indent 4 }}
#      {{- end }}
#    {{- end }}
matchExpressions:    
  - key: kubernetes.io/metadata.name
    operator: NotIn
    values:
      - "kube-system"
      - "openshift*"
      - "default"
      - "kubde-info"


# -- Security context configuration for containers
# <br />
# Example include:
# {{- if .Values.securityContext }}
# {{ include "tpl.securityContext" .Values.securityContext | indent 2 }}
# {{- end }}
securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  runAsNonRoot: true
  readOnlyRootFilesystem: true

# -- Pod-level security context
# <br />
# Example include:
# {{- if .Values.podSecurityContext }}
# {{ include "tpl.podSecurityContext" .Values.podSecurityContext | indent 2 }}
# {{- end }}
podSecurityContext:
  runAsUser: 1001
  runAsGroup: 3001
  fsGroup: 2001
  runAsNonRoot: true

# -- PodDisruptionBudget
# <br />
# Example include:
# {{- if .Values.podDisruptionBudget }}
# {{ include "tpl.podDisruptionBudget" .Values.podDisruptionBudget | indent 2 }}
# {{- end }}
podDisruptionBudget:
  name: "test-pdb"
  namespace: "test-namespace"
  additionalAnnotations:
    test-annotation: "test-annotation"
  additionalLabels:
    test-label: "test-label"
  minAvailable: 1
# maxUnavailable and minAvailable are mutually exclusive
#  maxUnavailable: 1
  matchLabels:
    app: test-app
    vendor: test-vendor
  matchExpressions:
    - key: app
      operator: In
      values:
        - test-app
        - test-app-2
    - key: vendor
      operator: In
      values:
        - test-vendor
  unhealthyPodEvictionPolicy: "AlwaysAllow"
