apiVersion: v2
name: helper-proj-onboarding
description: This Chart shall deploy namespaces and their depending resources, like NetworkPolicies or Quotas etc.
version: 1.0.44
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-proj-onboarding
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/helping.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
dependencies:
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - helper
  - subchart
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: "Signing Chart"
    - kind: fixed
      description: "changed the ifelse definitions for resourcequota for tshirt sizes"
    - kind: fixed
      description: "changed the way default network policies are managed"
    - kind: fixed
      description: "streamlined the creation of AppProject"
    - kind: added
      description: "added README and did some fixed"
    - kind: added
      description: "possibility to define egressIPs"
    - kind: added
      description: "added dependency tp tpl library"
    - kind fixed
      description: "fullaccess of argocd project now also allows to define the own repository for a developer"
